In [30]:
import pandas as pd
import io
import requests
import json

In [7]:
base_url = "https://api.nilu.no"

In [8]:
air_quality_index_url = "/aq/historical/{fromtime}/{totime}/{latitude}/{longitude}/{radius}?components={components}"

In [4]:
https://api.nilu.no/aq/historical/2017-01-01/2017-01-02/59.89869/10.81495/3.0?components=no2;pm10

SyntaxError: invalid syntax (<ipython-input-4-7954f17f0b73>, line 1)

In [9]:
start_date = "2017-01-01"
end_date = "2017-01-02"
lat = "59.89869"
lon = "10.81495"
rad = "3.0"
comp = "no2;pm10"

In [10]:
complete_url = base_url+air_quality_index_url.format(fromtime = start_date, totime = end_date, latitude = lat, longitude = lon, radius=rad, components = comp)
complete_url

'https://api.nilu.no/aq/historical/2017-01-01/2017-01-02/59.89869/10.81495/3.0?components=no2;pm10'

In [50]:
#from url to pandas dataframe
complete_url = base_url+air_quality_index_url.format(fromtime = start_date, totime = end_date, latitude = lat, longitude = lon, radius=rad, components = comp)
print(complete_url)

raw_data=requests.get(complete_url).content
raw_data_decoded = raw_data.decode('utf-8')
res = json.loads(raw_data_decoded)
res
df = pd.DataFrame.from_dict(res[0])

https://api.nilu.no/aq/historical/2017-01-01/2017-01-02/59.89869/10.81495/3.0?components=no2;pm10

In [60]:
df['fromTime'] = df.apply(lambda r: r['values']['fromTime'], axis=1)
df['toTime'] = df.apply(lambda r: r['values']['toTime'], axis=1)
df['value'] = df.apply(lambda r: r['values']['value'], axis=1)
df['qualityControlled'] = df.apply(lambda r: r['values']['qualityControlled'], axis=1)
df['index'] = df.apply(lambda r: r['values']['index'], axis=1)
df['color'] = df.apply(lambda r: r['values']['color'], axis=1)

In [ ]:
{'fromTime': '2017-01-01T00:00:00+01:00',
 'toTime': '2017-01-01T01:00:00+01:00',
 'value': 33.656246,
 'qualityControlled': True,
 'index': 1,
 'color': '6ee86e'}

In [62]:
df.head()

,id,zone,municipality,area,station,eoi,component,latitude,longitude,timestep,isVisible,unit,values,fromTime,toTime,value,qualityControlled,index,color
0,36,Stor-Oslo,Oslo,Oslo,Manglerud,NO0071A,NO2,59.89869,10.81495,3600,True,µg/m³,"{'fromTime': '2017-01-01T00:00:00+01:00', 'toT...",2017-01-01T00:00:00+01:00,2017-01-01T01:00:00+01:00,33.656246,True,1,6ee86e
1,36,Stor-Oslo,Oslo,Oslo,Manglerud,NO0071A,NO2,59.89869,10.81495,3600,True,µg/m³,"{'fromTime': '2017-01-01T01:00:00+01:00', 'toT...",2017-01-01T01:00:00+01:00,2017-01-01T02:00:00+01:00,66.923648,True,1,6ee86e
2,36,Stor-Oslo,Oslo,Oslo,Manglerud,NO0071A,NO2,59.89869,10.81495,3600,True,µg/m³,"{'fromTime': '2017-01-01T02:00:00+01:00', 'toT...",2017-01-01T02:00:00+01:00,2017-01-01T03:00:00+01:00,45.079216,True,1,6ee86e
3,36,Stor-Oslo,Oslo,Oslo,Manglerud,NO0071A,NO2,59.89869,10.81495,3600,True,µg/m³,"{'fromTime': '2017-01-01T03:00:00+01:00', 'toT...",2017-01-01T03:00:00+01:00,2017-01-01T04:00:00+01:00,63.750189,True,1,6ee86e
4,36,Stor-Oslo,Oslo,Oslo,Manglerud,NO0071A,NO2,59.89869,10.81495,3600,True,µg/m³,"{'fromTime': '2017-01-01T04:00:00+01:00', 'toT...",2017-01-01T04:00:00+01:00,2017-01-01T05:00:00+01:00,60.040693,True,1,6ee86e

In [48]:
df['values'][0]

{'fromTime': '2017-01-01T00:00:00+01:00',
 'toTime': '2017-01-01T01:00:00+01:00',
 'value': 33.656246,
 'qualityControlled': True,
 'index': 1,
 'color': '6ee86e'}

In [43]:
res[0]

{'id': 36,
 'zone': 'Stor-Oslo',
 'municipality': 'Oslo',
 'area': 'Oslo',
 'station': 'Manglerud',
 'eoi': 'NO0071A',
 'component': 'NO2',
 'latitude': 59.89869,
 'longitude': 10.81495,
 'timestep': 3600,
 'isVisible': True,
 'unit': 'µg/m³',
 'values': [{'fromTime': '2017-01-01T00:00:00+01:00',
   'toTime': '2017-01-01T01:00:00+01:00',
   'value': 33.656246,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T01:00:00+01:00',
   'toTime': '2017-01-01T02:00:00+01:00',
   'value': 66.923648,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T02:00:00+01:00',
   'toTime': '2017-01-01T03:00:00+01:00',
   'value': 45.079216,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T03:00:00+01:00',
   'toTime': '2017-01-01T04:00:00+01:00',
   'value': 63.750189,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T04:00:00+01:00',
   'toTime': '2017-01-01T05:00:00+01:00',
   'value': 60.040693,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T05:00:00+01:00',
   'toTime': '2017-01-01T06:00:00+01:00',
   'value': 40.123382,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T06:00:00+01:00',
   'toTime': '2017-01-01T07:00:00+01:00',
   'value': 23.945583,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T07:00:00+01:00',
   'toTime': '2017-01-01T08:00:00+01:00',
   'value': 39.285531,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T08:00:00+01:00',
   'toTime': '2017-01-01T09:00:00+01:00',
   'value': 20.969613,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T09:00:00+01:00',
   'toTime': '2017-01-01T10:00:00+01:00',
   'value': 29.914668,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T10:00:00+01:00',
   'toTime': '2017-01-01T11:00:00+01:00',
   'value': 26.948923,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T11:00:00+01:00',
   'toTime': '2017-01-01T12:00:00+01:00',
   'value': 53.85404,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T12:00:00+01:00',
   'toTime': '2017-01-01T13:00:00+01:00',
   'value': 60.636371,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T13:00:00+01:00',
   'toTime': '2017-01-01T14:00:00+01:00',
   'value': 67.90336,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T14:00:00+01:00',
   'toTime': '2017-01-01T15:00:00+01:00',
   'value': 114.729004,
   'qualityControlled': True,
   'index': 2,
   'color': 'ff9900'},
  {'fromTime': '2017-01-01T15:00:00+01:00',
   'toTime': '2017-01-01T16:00:00+01:00',
   'value': 31.941761,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T16:00:00+01:00',
   'toTime': '2017-01-01T17:00:00+01:00',
   'value': 40.508356,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T17:00:00+01:00',
   'toTime': '2017-01-01T18:00:00+01:00',
   'value': 40.723873,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T18:00:00+01:00',
   'toTime': '2017-01-01T19:00:00+01:00',
   'value': 32.197053,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T19:00:00+01:00',
   'toTime': '2017-01-01T20:00:00+01:00',
   'value': 27.516625,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T20:00:00+01:00',
   'toTime': '2017-01-01T21:00:00+01:00',
   'value': 26.227342,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T21:00:00+01:00',
   'toTime': '2017-01-01T22:00:00+01:00',
   'value': 60.8043,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T22:00:00+01:00',
   'toTime': '2017-01-01T23:00:00+01:00',
   'value': 57.580885,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'},
  {'fromTime': '2017-01-01T23:00:00+01:00',
   'toTime': '2017-01-02T00:00:00+01:00',
   'value': 70.276346,
   'qualityControlled': True,
   'index': 1,
   'color': '6ee86e'}]}